export const data = {
  code: 0,
  result: {
    standardAdList: [],
    liteAdList: [
      {
        _id: "6286411618d341001d0b01dc",
        gymName: "부개 바디패션짐 본점 24시",
        gymPhotoBig:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/180dc6e41623842c1/NtZrSjU5q8XNDU3AEnkx1TXgn5xEzH18Hu.센터 Big 복사.jpg",
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/180dc6e41623842c1/NtZrSjU5q8XNDU3AEnkx1TXgn5xEzH18Hu.센터 Big 복사.jpg",
        address: "인천 부평구 부개동",
        location: [126.7396483329674, 37.50401428488515],
        review: {
          rate: 4.23,
          count: 13,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "14b72fa6-9330-4201-ab76-b78833ddc6c3",
          productId: "d8f12223-6910-4eab-8e21-b92c926b4d1b",
          productName: "헬스 회원권",
          defaultPrice: 249000,
          dagymPrice: 223000,
          dagymPriceRemainingCount: 1,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "️O.T 1회(선택사항)",
        },
        service: {
          free: "",
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: true,
      },
    ],
    centerList: [
      {
        _id: "629efec04600ae001d30a87b",
        gymName: "삼산 별필라테스&플라잉요가 ",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1813d131f952ea9331/4K8g5puN9cxSiyAp4tn59XEC3zj2kUCY3x1nRzn8TR9Z.jpg",
        address: "인천 부평구 삼산동",
        location: [126.7324645, 37.5157563],
        review: {
          rate: 5,
          count: 6,
        },
        isWomenOnly: true,
        isReservationRequired: true,
        isLowestPrice: false,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "7b3812d0-c65a-4990-b496-f94f9f22463c",
          productId: "b29cd43c-1ded-44c8-8c1b-d9752ea3ff3b",
          productName: "Total 회원권",
          defaultPrice: 1468500,
          dagymPrice: 1468500,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 15,
          count: 150,
        },
        exhibitionRemainingCount: null,
        tags: ["필라테스", "플라잉요가"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "5a16becae3426a253d9ae19f",
        gymName: "갈산 인천 베스트 클라이밍",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/15fe8d946e857f0b2/Big)BestClimbing.jpg",
        address: "인천 부평구 갈산동",
        location: [126.726102, 37.517559],
        review: {
          rate: 4.75,
          count: 6,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "c398c64d-62a9-40b9-928b-9d5e9d8f9390",
          productId: "3181ea0f-43e4-4c46-b883-ce777694dd11",
          productName: "클라이밍",
          defaultPrice: 250000,
          dagymPrice: 250000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 3,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["클라이밍"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "5a16bfd5e3426a253d9ae1a1",
        gymName: "갈산 팀복싱짐 휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/15fe8dd5b822a4e411/2ZvFt3iwKpQBnJ6sR5XDuP6vPMXcsGxHsPUB.background_photo.jpg",
        address: "인천 부평구 갈산동",
        location: [126.725725, 37.511593],
        review: {
          rate: 4.88,
          count: 2,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "72f21748-fe67-4690-9e7f-dbfc8a532b97",
          productId: "888097b8-2114-4a3e-b11a-81b08a0501f0",
          productName: "헬스",
          defaultPrice: 360000,
          dagymPrice: 360000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["복싱", "헬스"],
        program: {
          free: " / ",
        },
        service: {
          free: "운동복 / 수건 / ",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "6478433bf3cbba001d5f4f55",
        gymName: "부평 노력의천재 헬스&PT",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18875c6a0c120fe43/kXkA9EVriGUYZArwZQn5eXDnp9mPDznf4Rbs3HXMks.jpg",
        address: "인천 부평구 갈산동",
        location: [126.7235618353383, 37.5159250198634],
        review: {
          rate: 5,
          count: 2,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "33c29f19-2b73-45d3-abfa-b2231c3041e0",
          productId: "9d3a8cec-c373-431c-b96c-da74ff389722",
          productName: "헬스 회원권",
          defaultPrice: 396000,
          dagymPrice: 396000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️수건",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
      },
      {
        _id: "59f61259b0993a41223b764d",
        gymName: "삼산 테크노짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/15f6937ac63467f188/2YUaDbsiTfQiNNsQYP4q6vDbwgDj5V5HAjFv.센터 Big 복사.jpg",
        address: "인천 부평구 삼산동",
        location: [126.735858, 37.507097],
        review: {
          rate: 5,
          count: 37,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "55106639-1ac0-4edb-8e58-25b8809438d5",
          productId: "4783bd88-3d70-49ef-b20d-41c12bcfea96",
          productName: "헬스 회원권",
          defaultPrice: 506000,
          dagymPrice: 501000,
          dagymPriceRemainingCount: 2,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "-G.X [파워덤벨 / 코어트레이닝 / 요가 / 댄스에어로빅 / 전신스트레칭 / S-라인체조] /  / O.T 1회 (*간단한 기구설명 및 동기부여)",
        },
        service: {
          free: "주차 3시간 / 인바디 측정",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 1,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
      },
      {
        _id: "62e7726ff9efad001d8e579b",
        gymName: "갈산 고바디 피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/182581702b9321a8ed/4K8gHXmjHsg3PCGKpjqdpNiBh9WZGPoGgDS1XVbPpb2w.jpg",
        address: "인천 부평구 청천동",
        location: [126.7209644331409, 37.51707444582458],
        review: {
          rate: 4.67,
          count: 3,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "ae7780cd-c849-462a-bc2e-905023f76135",
          productId: "10e8e071-6440-4cfc-baae-e62af0541bc5",
          productName: "헬스 회원권",
          defaultPrice: 600000,
          dagymPrice: 600000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "Wi-fi / 주차장 / 수건",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "62a6c095123b8b001d5372bb",
        gymName: "부개 유알짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1815b6048d82eaa98f/2YAY27HTZEX5jrM59yHhRxJjVP6RJZ5fpEMb.background_photo.jpg",
        address: "인천 부평구 부개동",
        location: [126.734291295753, 37.504187692879],
        review: {
          rate: 5,
          count: 7,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "59143dd2-68db-4401-afb1-e300be2240c8",
          productId: "4be962d4-12d2-4e51-8153-88b8563c6b51",
          productName: "2025 초특가 회원권",
          defaultPrice: 440000,
          dagymPrice: 418000,
          dagymPriceRemainingCount: 3,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "30회 PT 등록시! 회원복 & 락커 제공! / 수건 무료 제공 / 일일 입장제한 X / 등록시 무료 피티 1회 제공",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "680f2c0a16cdca7bb320e4cc",
        gymName: "부평 아름다훈PT",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/2d2f90e7-7006-4e4b-8633-7d05dc6407ac/1745824358582_8aa5dd26-6c8a-4aae-ae79-36cfe21dcab6.jpg",
        address: "인천 부평구 부평동",
        location: [126.7257838, 37.5055506],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "c5da6a3c-6f3e-47b0-8b35-9eaf86aef550",
          productId: "f9e121c0-2d31-47f6-ad38-f309b238d86d",
          productName: "1년권",
          defaultPrice: 363000,
          dagymPrice: 326700,
          dagymPriceRemainingCount: null,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "681c8b907f38b24551c5e818",
        gymName: "작전 품태권도",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/4952582f-9184-46cb-892a-d98749bf8d2f/1746597051410_5c2aa690-6dee-44bc-ba8a-71fd791eae18.jfif",
        address: "인천 계양구 작전동",
        location: [126.7300927, 37.5268178],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "72cb3371-0f64-492a-b8a8-97de6b98eb27",
          productId: "14905db6-ffd6-4bed-b429-0ff01177de26",
          productName: "태권도 월 이용권 (주3회)",
          defaultPrice: 150000,
          dagymPrice: 135000,
          dagymPriceRemainingCount: null,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 1,
          count: 12,
        },
        exhibitionRemainingCount: null,
        tags: ["태권도"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "65a52bbcf0f23f001d6bb16e",
        gymName: "작전 센스짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18d0d32d9a913b7ef0/41jo4gjm5q9TUKmwg53dk154egtCNQk9GrBL.센터 Big 복사.jpg",
        address: "인천 계양구 작전동",
        location: [126.7337819116077, 37.52778313525792],
        review: {
          rate: 5,
          count: 13,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "315ac5f6-307e-420c-ba2a-dac1c24ec4d3",
          productId: "f72948f2-02f9-4dd0-873c-f4f30ec4d81e",
          productName: "헬스 회원권",
          defaultPrice: 499000,
          dagymPrice: 330000,
          dagymPriceRemainingCount: 4,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 2시간",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "625e4ae305aa82001d4f09df",
        gymName: "작전 요가클랜",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/180405487885ee3382/4K8ftEwtVZTrTMB2wqnVGaNLD9uER67yiRDeQkoh3rsh.jpg",
        address: "인천 계양구 작전동",
        location: [126.7339333494811, 37.52814612874903],
        review: {
          rate: 5,
          count: 2,
        },
        isWomenOnly: false,
        isReservationRequired: true,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "55d96e68-59ec-4303-be88-c278c3772b4d",
          productId: "f04cb54a-3e0e-42c0-8d31-ccd806ef7630",
          productName: "요가 회원권 (횟수제)",
          defaultPrice: 320000,
          dagymPrice: 288000,
          dagymPriceRemainingCount: null,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 2,
          count: 16,
        },
        exhibitionRemainingCount: null,
        tags: ["요가"],
        program: {
          free: "",
        },
        service: {
          free: "- 공용락커 / ※샤워시설 없습니다.",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "61837da96bdf9700391007f7",
        gymName: "부평구청 타임짐휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/17ce9a2dc2f2ea44fe/4K7xr2pEyhVMzEc5bz6PhzPHh3kDe3k4dKF3fvQKmHdh.jpg",
        address: "인천 부평구 부평동",
        location: [126.719892, 37.505882],
        review: {
          rate: 5,
          count: 3,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "ecfbc208-e939-49b0-9e62-761e4219d1fd",
          productId: "e367ee19-1b4c-438e-aee6-dc4bd3cf620d",
          productName: "헬스 이용권",
          defaultPrice: 396000,
          dagymPrice: 359000,
          dagymPriceRemainingCount: 1,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️가변주차가능 / ️샤워시설 / ️WI-FI / ️수건 / ️인바디 검사",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "636b0d23d6679f001d132deb",
        gymName: "부평 PT시작",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1845a2b539e5f19578/4K8ggnJZ5AD7w3khCU7XVtjhLAGinLX5NPdxT2qVqVpT.jpg",
        address: "인천 부평구 부평동",
        location: [126.7210351983935, 37.50489982808945],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: true,
        isLowestPrice: false,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "5968967a-f69b-4402-80aa-b4e07417737a",
          productId: "99538506-1293-4477-a144-60fa795a2a57",
          productName: "1:1 PT ",
          defaultPrice: 2750000,
          dagymPrice: 2750000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 6,
          count: 50,
        },
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 개인락커 / 커피이용",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "67a43fdc3354349be3637718",
        gymName: "청천 킹짐 6호점",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/50f31b79-9bbc-45bc-9709-5c8729aa18bb/1738557466108_a77c5720-d64f-4e6b-b833-ae1178e731ca.jpg",
        address: "인천 부평구 청천동",
        location: [126.71772724210626, 37.50636961372883],
        review: {
          rate: 4.56,
          count: 9,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "7502dbf0-2e24-4cd5-aaaa-d89256e9a57e",
          productId: "f3435dab-2d72-4d95-b140-d6ccb07b4315",
          productName: "헬스 이용권2",
          defaultPrice: 328900,
          dagymPrice: 328900,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "무료pt",
        },
        service: {
          free: "무료주차",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 1,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
      },
      {
        _id: "6386b97eb54b10001dec4fe3",
        gymName: "부평 mgym",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/184c64497a13d462cd/NQabER8mYacC1vgShPrpLDJKrgyTQCVVj1.Big_241226_부평_mgym_19.jpg",
        address: "인천 부평구 부평동",
        location: [126.7296525161124, 37.49880655738467],
        review: {
          rate: 5,
          count: 3,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "3258eb8f-f052-49fe-a2f2-c998a86030fe",
          productId: "90143067-704f-46c3-a81b-1b3f126d7ff1",
          productName: "헬스 회원권",
          defaultPrice: 396000,
          dagymPrice: 396000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 4시간",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: true,
        isDagymRecommended: true,
      },
      {
        _id: "65951ec730790a001d125947",
        gymName: "작전 라미피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18cce803b2910ca686/2ZvjgjpzECC3id8StqFt3TLyrKBXhh4ra2Nv.센터 Big 복사.jpg",
        address: "인천 계양구 작전동",
        location: [126.7232287018712, 37.52955636832216],
        review: {
          rate: 5,
          count: 1,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "0b0a0597-9464-4c78-ac44-4d51f56afa85",
          productId: "a5aa7f21-0d98-44d4-9f2b-e593a36927cb",
          productName: "헬스 회원권",
          defaultPrice: 396000,
          dagymPrice: 356400,
          dagymPriceRemainingCount: null,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️수건 / ️주차",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 1,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
      },
      {
        _id: "60dbdeb57c7b87003995a819",
        gymName: "상동 크라운짐휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/7511811f-8ad7-4f4c-8d01-b1665923f67d/1751870696567_f45c5027-5fa1-40bd-8f11-c1452a3a35a9.jpg",
        address: "경기 부천시 원미구 상동",
        location: [126.7517305083644, 37.50756798804051],
        review: {
          rate: 5,
          count: 36,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "b8e8592e-b14d-4f1e-acf3-37031a3333e4",
          productId: "d4396998-5866-44c4-9d44-7b0e7707f65a",
          productName: "헬스 + 운동복 + 락커",
          defaultPrice: 440000,
          dagymPrice: 440000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "O.T (상시지도)",
        },
        service: {
          free: "운동복 / 수건 / 락커 / 주차 2시간 / Wi-fi",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "66c7ef9801d0e4001dd151e9",
        gymName: "부개 용인대 런주짓수&런킥복싱",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1917cffea84371eb27/2YBg2GXAJthTsdHAGWEndNv5X9p7uUAu7kHe.background_photo.jpg",
        address: "인천 부평구 부개동",
        location: [126.7354623734008, 37.49800880688532],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "8c1cbc2a-e06c-4e17-825d-b2854ec329b2",
          productId: "34a066e2-f39f-44d8-9d28-7510060a03d2",
          productName: "용인대 런주짓수 & 런킥복싱 회원권",
          defaultPrice: 1200000,
          dagymPrice: 1200000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["주짓수", "킥복싱"],
        program: {
          free: "",
        },
        service: {
          free: "주차 무료 서비스",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "680b22779ab134bfd935cef6",
        gymName: "작전 우리검도관",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/0c057b29-20ee-4e70-a5b7-38501c8ef9c4/1745556804832_00611c91-b388-4076-a175-97378681d0ba.jpg",
        address: "인천 계양구 작전동",
        location: [126.7335396, 37.5318368],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "0e7eb901-f12f-49d1-9ab2-9287e38c2e3e",
          productId: "be62ed78-0bd2-415c-a2f0-5a007e4c7402",
          productName: "검도 월 이용권(주3회)",
          defaultPrice: 150000,
          dagymPrice: 150000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 1,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["검도"],
        program: {
          free: "주자장",
        },
        service: {
          free: "",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
      {
        _id: "68118ef3232af8b05e5f8316",
        gymName: "작전 청춘유도관",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/a9afdbfd-3240-40c9-8cb7-5b439c08d432/1747709749451_9b0c3cd4-2f11-45f8-ba9e-3ecf3d5484c2.jpg",
        address: "인천 계양구 작전동",
        location: [126.7335396, 37.5318368],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "6f4ac69f-4887-44d4-8b35-50849d3cd780",
          productId: "da16754f-be2d-46d4-96a6-9bfbda87a9f0",
          productName: "유도 이용권",
          defaultPrice: 420000,
          dagymPrice: 399000,
          dagymPriceRemainingCount: null,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 3,
          count: null,
        },
        exhibitionRemainingCount: null,
        tags: ["유도"],
        program: {
          free: "",
        },
        service: {
          free: "무료",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
      },
    ],
  },
};
